### ISSUE TITLE
Align toml properties for backward compatibility

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet-sdk#117]
While testing some existing `toml`s from Polkadot-sdk it came to our attention that there are properties on the toml that should be (?) optional in order to allow SDK to backwards work with existing toml files and tests;

An example is one of the [simpliest tomls](https://github.com/paritytech/polkadot-sdk/blob/0a6dfdf973b8e7b669eda6e2ed202fb3549a20b9/polkadot/zombienet_tests/smoke/0001-parachains-smoke-test.toml);

In order to try to spawn this network the following properties had to be (erroneously) added:
- node_spawn_timeout (in `[settings]`)
- default_command (in `[relaychain]`)
- is_bootnode (in `[[relaychain.nodes]]`)
- balance = 200000000, cumulus_based = true, chain="some" (in `[[parachains]]`)

We need to test that our code supports backward tests

**Comment by ordian** [comment]
A few things I noticed are not backwards compatible:
```toml
# doesn't work:
[[relaychain.node_groups]] 
count = 2
# workaround:
[[relaychain.nodes]]
name = "node-0"
[[relaychain.nodes]]
name = "node-1"

# doesn't work
[parachains.collator]
# workaround:
[[parachains.collators]]

# doesn't work
[relaychain.genesis.runtimeGenesis.patch.configuration.config]
```
