### ISSUE TITLE
Cannot run network with `polkadot-local` relaychain

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/zombienet-sdk#255]
### Issue Description

I am trying to use the `polkadot-local` relay spec to set up a ZN network. Nevertheless, the parachain never gets to produce any blocks, and no errors is generated in the logs. I am not sure if this is how `polkadot-local` is supposed (not) to work, or if I am missing some additional configurations.

### Steps to reproduce the issue

Use the following basic network setup config:

```yaml
settings:
    node_verifier: "None"
    provider: "kubernetes"
    timeout: 18000

relaychain:
    chain: polkadot-local
    # Generated from https://github.com/polkadot-fellows/runtimes with `cargo run -- polkadot-local`
    chain_spec_path: runtimes/spiritnet/polkadot-local-v1.3.2-e220854.json
    default_image: "{{RELAY_IMAGE}}"
    nodes:
        - name: "relay-alice"
          rpc_port: "{{RELAY_RPC}}"
          args:
              - "-lparachain=debug"
        - name: "relay-bob"
        - name: "relay-charlie"

parachains:
    - id: 2086
      chain: spiritnet-dev

      collators:
          - command: "node-executable"
            image: "{{PARA_IMAGE}}"
            name: "para-alice"
            rpc_port: "{{PARA_RPC}}"
          - command: "node-executable"
            image: "{{PARA_IMAGE}}"
            name: "para-bob"
```

the following `.env` file:

```
RELAY_IMAGE=parity/polkadot:v1.15.2
RELAY_RPC=50001
PARA_IMAGE=kiltprotocol/kilt-node:1.14.3
PARA_RPC=50010
```

and the following command:

`env $(cat runtimes/spiritnet/.env | xargs) yarn zombienet --spawn-concurrency=3 spawn runtimes/spiritnet/network.yaml`

### Describe the results you received

The parachain does not produce nor attempts to author any blocks.

### Describe the results you expected

Either an error or actually blocks being produced.

### Zombienet version

1.3.109

### Provider

Kubernetes

### Provider version

```yaml
kubectl version v1.26.1
```

### Upstream Latest Release

Yes

### Additional environment details

See snippets above.

### Additional information

It works if a replace the custom chainspec with `rococo-local`.
